version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["security", "chore"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels: ["ci", "chore"]
