blank_issues_enabled: false
contact_links:
  - name: Documentation (Glossary & Collaboration Rules)
    url: https://github.com/nakanaka07/sado-restaurant-map/tree/main/docs
    about: 用語・品質ゲート・協業プロンプトを参照してください
