name: Coverage Badge

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  gen-badge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch coverage summary artifact from CI run
        id: fetch
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          api="https://api.github.com/repos/${REPO}/actions/runs/${RUN_ID}/artifacts"
            url=$(curl -sf -H "Authorization: Bearer ${GH_TOKEN}" -H 'Accept: application/vnd.github+json' "$api" | jq -r '.artifacts[] | select(.name=="coverage-summary") | .archive_download_url' || true)
            if [ -z "$url" ]; then echo "Artifact not found"; exit 1; fi
            curl -L -H "Authorization: Bearer ${GH_TOKEN}" -o artifact.zip "$url"
            unzip artifact.zip || (echo 'Unzip failed'; ls -al; exit 1)
            if [ ! -f coverage-summary.json ]; then echo 'coverage-summary.json missing'; exit 1; fi
            jq '.total.lines.pct' coverage-summary.json | xargs printf 'pct=%.*f\n' 0 >> $GITHUB_OUTPUT

      - name: Generate badge svg
        id: badge
        run: |
          pct=${{ steps.fetch.outputs.pct }}
          color=blue
          if [ "$pct" -ge 90 ]; then color=brightgreen; elif [ "$pct" -ge 75 ]; then color=green; elif [ "$pct" -ge 60 ]; then color=yellow; elif [ "$pct" -ge 45 ]; then color=orange; else color=red; fi
          echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"150\" height=\"20\"><linearGradient id=\"b\" x2=\"0\" y2=\"100%\"><stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/><stop offset=\"1\" stop-opacity=\".1\"/></linearGradient><mask id=\"a\"><rect width=\"150\" height=\"20\" rx=\"3\" fill=\"#fff\"/></mask><g mask=\"url(#a)\"><rect width=\"80\" height=\"20\" fill=\"#555\"/><rect x=\"80\" width=\"70\" height=\"20\" fill=\"#$color\"/><rect width=\"150\" height=\"20\" fill=\"url(#b)\"/></g><g fill=\"#fff\" text-anchor=\"middle\" font-family=\"Verdana,Geneva,DejaVu Sans,sans-serif\" text-rendering=\"geometricPrecision\" font-size=\"11\"><text x=\"40\" y=\"15\">coverage</text><text x=\"115\" y=\"15\">${pct}%</text></g></svg>" > coverage-badge.svg

      - name: Commit badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          mkdir -p assets
          mv coverage-badge.svg assets/
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add assets/coverage-badge.svg
          if git diff --cached --quiet; then
            echo 'No changes to commit'
            exit 0
          fi
          git commit -m "chore: update coverage badge"
          git push || echo 'Push failed (protected branch?)'

      - name: Summary
        run: |
          echo "Coverage badge updated: ${{ steps.fetch.outputs.pct }}%" >> $GITHUB_STEP_SUMMARY

      - name: Done
        run: echo "Badge workflow finished"
