# .github/workflows/update_data.yml

name: Update Sado Restaurant Data

on:
  # 月1回の自動実行（毎月1日の02:00 UTC = 11:00 JST）
  schedule:
    - cron: "0 2 1 * *"
  # 手動実行
  workflow_dispatch:
    inputs:
      target_data:
        description: "更新対象データ"
        required: false
        default: "all"
        type: choice
        options:
          - "all"
          - "restaurants"
          - "parkings"
          - "toilets"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run scraper
        run: python scraper/places_data_updater.py
        env:
          # GitHub Secretsから環境変数を渡す
          PLACES_API_KEY: ${{ secrets.PLACES_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          # コスト最適化: 手動実行時のみ指定データを更新
          TARGET_DATA: ${{ github.event.inputs.target_data || 'all' }}
          # API呼び出し間隔を調整（デフォルト: 2秒）
          API_DELAY: "2"
