apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-master-1:6379
    basicAuth: false
    version: 1
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: sado_restaurant_map
    user: postgres
    basicAuth: false
    version: 1
    editable: true
    jsonData:
      sslmode: require
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
    secureJsonData:
      password: ${DB_PASSWORD}
